create extension if not exists pgcrypto;
create table public.businesses(id uuid primary key default gen_random_uuid(),name text not null,created_at timestamptz not null default now());
create table public.profiles(id uuid primary key references auth.users(id) on delete cascade,business_id uuid references public.businesses(id) on delete cascade,full_name text,role text not null default 'owner' check(role in('owner','manager','staff')),created_at timestamptz not null default now());
create table public.ingredients(id uuid primary key default gen_random_uuid(),business_id uuid not null references public.businesses(id) on delete cascade,name text not null,purchase_unit text not null,purchase_price numeric(14,2) not null default 0,base_unit text not null,units_per_purchase numeric(14,4) not null default 1,notes text,active boolean not null default true,unique(business_id,name));
create table public.products(id uuid primary key default gen_random_uuid(),business_id uuid not null references public.businesses(id) on delete cascade,name text not null,category text not null,current_price numeric(14,2) not null default 0,active boolean not null default true,unique(business_id,name));
create table public.recipes(id uuid primary key default gen_random_uuid(),business_id uuid not null references public.businesses(id) on delete cascade,product_id uuid not null references public.products(id) on delete cascade,yield_quantity numeric(14,4) not null default 1,notes text,unique(product_id));
create table public.recipe_items(id uuid primary key default gen_random_uuid(),recipe_id uuid not null references public.recipes(id) on delete cascade,ingredient_id uuid not null references public.ingredients(id),quantity numeric(14,4) not null,unique(recipe_id,ingredient_id));
create table public.fixed_costs(id uuid primary key default gen_random_uuid(),business_id uuid not null references public.businesses(id) on delete cascade,name text not null,monthly_amount numeric(14,2) not null default 0,active boolean not null default true);
create table public.sales_days(id uuid primary key default gen_random_uuid(),business_id uuid not null references public.businesses(id) on delete cascade,sale_date date not null,revenue numeric(14,2) not null default 0,orders integer not null default 0,channel text not null default 'mixed',unique(business_id,sale_date,channel));
