create or replace function public.current_business_id() returns uuid language sql stable security definer set search_path=public as $$ select business_id from public.profiles where id=auth.uid() $$;
drop policy if exists "profiles own profile" on public.profiles;
create policy "profiles own profile" on public.profiles for select using(id=auth.uid());
drop policy if exists "business members read ingredients" on public.ingredients;
create policy "business members read ingredients" on public.ingredients for select using(business_id=public.current_business_id());
drop policy if exists "business managers manage ingredients" on public.ingredients;
create policy "business managers manage ingredients" on public.ingredients for all using(business_id=public.current_business_id() and exists(select 1 from public.profiles where id=auth.uid() and role in('owner','manager'))) with check(business_id=public.current_business_id());
drop policy if exists "business members read products" on public.products;
create policy "business members read products" on public.products for select using(business_id=public.current_business_id());
drop policy if exists "business managers manage products" on public.products;
create policy "business managers manage products" on public.products for all using(business_id=public.current_business_id() and exists(select 1 from public.profiles where id=auth.uid() and role in('owner','manager'))) with check(business_id=public.current_business_id());
