'use client';
import { useState, FormEvent } from 'react';
import { createClient } from '@/lib/supabase/client';
type I={id:string;business_id:string;name:string;purchase_unit:string;purchase_price:number;base_unit:string;units_per_purchase:number;notes:string|null};
export function IngredientsManager({initial,businessId}:{initial:I[];businessId:string}){
 const[items,setItems]=useState(initial),[edit,setEdit]=useState<I|null>(null),[msg,setMsg]=useState('');
 const empty:I={id:'',business_id:businessId,name:'',purchase_unit:'kg',purchase_price:0,base_unit:'g',units_per_purchase:1000,notes:''};
 async function save(e:FormEvent){e.preventDefault();if(!edit)return;const s=createClient();const payload={business_id:businessId,name:edit.name,purchase_unit:edit.purchase_unit,purchase_price:edit.purchase_price,base_unit:edit.base_unit,units_per_purchase:edit.units_per_purchase,notes:edit.notes};if(edit.id){const{data,error}=await s.from('ingredients').update(payload).eq('id',edit.id).select().single();if(error){setMsg(error.message);return}setItems(items.map(x=>x.id===edit.id?data:x))}else{const{data,error}=await s.from('ingredients').insert(payload).select().single();if(error){setMsg(error.message);return}setItems([...items,data])}setEdit(null);setMsg('Guardado correctamente')}
 async function del(id:string){if(!confirm('¿Borrar?'))return;const{error}=await createClient().from('ingredients').delete().eq('id',id);if(error){setMsg(error.message);return}setItems(items.filter(x=>x.id!==id))}
 return <><div className="toolbar"><h1>Ingredientes</h1><button className="btn" onClick={()=>setEdit(empty)}>Agregar</button></div>{msg&&<div className={msg.includes('correctamente')?'success':'error'}>{msg}</div>}{edit&&<section className="panel"><form onSubmit={save}><div className="form-grid"><div className="field"><label>Nombre</label><input value={edit.name} onChange={e=>setEdit({...edit,name:e.target.value})}/></div><div className="field"><label>Unidad compra</label><input value={edit.purchase_unit} onChange={e=>setEdit({...edit,purchase_unit:e.target.value})}/></div><div className="field"><label>Precio</label><input type="number" value={edit.purchase_price} onChange={e=>setEdit({...edit,purchase_price:Number(e.target.value)})}/></div><div className="field"><label>Unidad base</label><input value={edit.base_unit} onChange={e=>setEdit({...edit,base_unit:e.target.value})}/></div><div className="field"><label>Unidades por compra</label><input type="number" value={edit.units_per_purchase} onChange={e=>setEdit({...edit,units_per_purchase:Number(e.target.value)})}/></div><div className="field"><label>Notas</label><input value={edit.notes||''} onChange={e=>setEdit({...edit,notes:e.target.value})}/></div></div><div className="actions"><button className="btn">Guardar</button><button type="button" className="btn secondary" onClick={()=>setEdit(null)}>Cancelar</button></div></form></section>}<section className="panel"><div className="table-wrap"><table><thead><tr><th>Ingrediente</th><th>Unidad</th><th>Precio</th><th>Costo base</th><th></th></tr></thead><tbody>{items.map(i=><tr key={i.id}><td>{i.name}</td><td>{i.purchase_unit}</td><td>${Number(i.purchase_price).toLocaleString('es-AR')}</td><td>${(Number(i.purchase_price)/Number(i.units_per_purchase)).toLocaleString('es-AR',{maximumFractionDigits:2})}/{i.base_unit}</td><td className="actions"><button className="btn secondary" onClick={()=>setEdit(i)}>Editar</button><button className="btn danger" onClick={()=>del(i.id)}>Borrar</button></td></tr>)}</tbody></table></div></section></>;
}
