'use client';
import{FormEvent,useState}from"react";import{createClient}from"@/lib/supabase/client";
type I={id:string;ingredient_id:string;current_quantity:number;minimum_quantity:number;target_quantity:number;ingredients:{name:string;base_unit:string}|null};
export function InventoryManager({initial}:{initial:I[]}){const[items,setItems]=useState(initial),[sel,setSel]=useState<I|null>(null),[qty,setQty]=useState(0),[type,setType]=useState('purchase'),[note,setNote]=useState(''),[min,setMin]=useState(0),[target,setTarget]=useState(0),[msg,setMsg]=useState('');
async function reload(){const{data,error}=await createClient().from('inventory_levels').select('id,ingredient_id,current_quantity,minimum_quantity,target_quantity,ingredients(name,base_unit)').order('updated_at',{ascending:false});if(error){setMsg(error.message);return}setItems((data||[]) as unknown as I[])}
function open(i:I){setSel(i);setMin(Number(i.minimum_quantity));setTarget(Number(i.target_quantity));setQty(0);setNote('')}
async function thresholds(){if(!sel)return;const{error}=await createClient().rpc('update_inventory_thresholds',{p_ingredient_id:sel.ingredient_id,p_minimum:min,p_target:target});if(error){setMsg(error.message);return}setMsg('Mínimos guardados');await reload()}
async function adjust(e:FormEvent){e.preventDefault();if(!sel||qty===0)return;let q=qty;if(type==='waste')q=-Math.abs(q);if(type==='purchase'||type==='return')q=Math.abs(q);const{error}=await createClient().rpc('adjust_stock',{p_ingredient_id:sel.ingredient_id,p_quantity:q,p_type:type,p_note:note||null});if(error){setMsg(error.message);return}setSel(null);setMsg('Movimiento registrado');await reload()}
return <><div className="toolbar"><div><h1 className="page-title">Inventario</h1><p className="page-subtitle">Stock, mínimos y compras sugeridas.</p></div></div>{msg&&<div className={msg.includes('guardados')||msg.includes('registrado')?'success':'error'}>{msg}</div>}{sel&&<section className="panel"><h2>{sel.ingredients?.name}</h2><div className="form-grid"><div className="field"><label>Mínimo</label><input type="number" value={min} onChange={e=>setMin(Number(e.target.value))}/></div><div className="field"><label>Objetivo</label><input type="number" value={target} onChange={e=>setTarget(Number(e.target.value))}/></div></div><button className="btn secondary" onClick={thresholds}>Guardar mínimos</button><form onSubmit={adjust}><div className="form-grid"><div className="field"><label>Movimiento</label><select value={type} onChange={e=>setType(e.target.value)}><option value="purchase">Compra</option><option value="adjustment">Ajuste</option><option value="waste">Merma</option><option value="return">Devolución</option></select></div><div className="field"><label>Cantidad ({sel.ingredients?.base_unit})</label><input type="number" step="0.01" value={qty} onChange={e=>setQty(Number(e.target.value))}/></div><div className="field"><label>Nota</label><input value={note} onChange={e=>setNote(e.target.value)}/></div></div><div className="actions"><button className="btn">Registrar</button><button type="button" className="btn secondary" onClick={()=>setSel(null)}>Cancelar</button></div></form></section>}<section className="panel"><div className="table-wrap"><table><thead><tr><th>Ingrediente</th><th>Stock</th><th>Mínimo</th><th>Objetivo</th><th>A comprar</th><th>Estado</th><th></th></tr></thead><tbody>{items.map(i=>{const c=Number(i.current_quantity),m=Number(i.minimum_quantity),t=Number(i.target_quantity),buy=Math.max(t-c,0),crit=c<=m;return <tr key={i.id}><td>{i.ingredients?.name}</td><td>{c.toLocaleString('es-AR')} {i.ingredients?.base_unit}</td><td>{m}</td><td>{t}</td><td>{buy.toLocaleString('es-AR')}</td><td><span className={`badge ${crit?'dangerText':'good'}`}>{crit?'Reponer':'Bien'}</span></td><td><button className="btn secondary" onClick={()=>open(i)}>Editar</button></td></tr>})}</tbody></table></div></section></>}
