\'use client\';
import {useMemo,useState} from 'react'; import {createClient} from '@/lib/supabase/client';
type P={id:string;name:string;category:string;current_price:number}; type C=P&{quantity:number};
const money=(v:number)=>new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS',maximumFractionDigits:0}).format(v||0);
export function PosManager({products}:{products:P[]}){const[cart,setCart]=useState<C[]>([]),[cat,setCat]=useState('Todos'),[search,setSearch]=useState(''),[pay,setPay]=useState('efectivo'),[channel,setChannel]=useState('mostrador'),[discount,setDiscount]=useState(0),[msg,setMsg]=useState(''),[saving,setSaving]=useState(false);
const cats=useMemo(()=>['Todos',...Array.from(new Set(products.map(p=>p.category)))],[products]); const filtered=products.filter(p=>(cat==='Todos'||p.category===cat)&&p.name.toLowerCase().includes(search.toLowerCase())); const subtotal=cart.reduce((a,i)=>a+Number(i.current_price)*i.quantity,0); const total=Math.max(subtotal-discount,0);
function add(p:P){setCart(c=>{const x=c.find(i=>i.id===p.id);return x?c.map(i=>i.id===p.id?{...i,quantity:i.quantity+1}:i):[...c,{...p,quantity:1}]})} function qty(id:string,q:number){setCart(c=>q<=0?c.filter(i=>i.id!==id):c.map(i=>i.id===id?{...i,quantity:q}:i))}
async function finish(){if(!cart.length){setMsg('El carrito está vacío.');return}setSaving(true);const{error}=await createClient().rpc('register_order',{p_items:cart.map(i=>({product_id:i.id,quantity:i.quantity})),p_payment_method:pay,p_channel:channel,p_discount:discount,p_customer_name:null,p_note:null});setSaving(false);if(error){setMsg(error.message);return}setCart([]);setDiscount(0);setMsg('Venta registrada correctamente.');}
return <><h1 className="page-title">Punto de Venta</h1>{msg&&<div className={msg.includes('correctamente')?'success':'error'}>{msg}</div>}<div className="pos-layout"><section className="panel"><input className="pos-search" placeholder="Buscar producto" value={search} onChange={e=>setSearch(e.target.value)}/><div className="pos-categories">{cats.map(c=><button key={c} className={`btn ${cat===c?'':'secondary'}`} onClick={()=>setCat(c)}>{c}</button>)}</div><div className="product-grid">{filtered.map(p=><button className="product-tile" key={p.id} onClick={()=>add(p)}><strong>{p.name}</strong><span>{p.category}</span><b>{money(Number(p.current_price))}</b></button>)}</div></section><aside className="panel cart-panel"><h2>Pedido</h2>{cart.map(i=><div className="cart-row" key={i.id}><div><strong>{i.name}</strong><small>{money(Number(i.current_price))}</small></div><div className="qty-controls"><button onClick={()=>qty(i.id,i.quantity-1)}>−</button><span>{i.quantity}</span><button onClick={()=>qty(i.id,i.quantity+1)}>+</button></div><strong>{money(Number(i.current_price)*i.quantity)}</strong></div>)}<div className="form-grid"><div className="field"><label>Canal</label><select value={channel} onChange={e=>setChannel(e.target.value)}><option value="mostrador">Mostrador</option><option value="rappi">Rappi</option><option value="whatsapp">WhatsApp</option></select></div><div className="field"><label>Pago</label><select value={pay} onChange={e=>setPay(e.target.value)}><option value="efectivo">Efectivo</option><option value="mercado_pago">Mercado Pago</option><option value="debito">Débito</option><option value="credito">Crédito</option></select></div><div className="field"><label>Descuento</label><input type="number" min="0" value={discount} onChange={e=>setDiscount(Number(e.target.value))}/></div></div><div className="totals"><div><span>Subtotal</span><strong>{money(subtotal)}</strong></div><div className="grand-total"><span>Total</span><strong>{money(total)}</strong></div></div><button className="btn checkout" onClick={finish} disabled={saving}>{saving?'Guardando...':'Cobrar pedido'}</button></aside></div></>}
